In [1]:
import pandas as pd

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [3]:
# read parquet file
df = pd.read_parquet("fragments.parquet")
df

              id  duration  cpu_count  cpu_usage
0        2132819     30000         16     1953.0
1        2132819     30000         16     2478.0
2        2132819     30000         16     2688.0
3        2132819     30000         16     2625.0
4        2132819     30000         16     2415.0
...          ...       ...        ...        ...
2323470  2177952     30000         16    28686.0
2323471  2177952     30000         16    29799.0
2323472  2177952     30000         16    30744.0
2323473  2177952     30000         16    31164.0
2323474  2177952     30000         16    31290.0

[2323475 rows x 4 columns]

In [5]:
df = pd.read_parquet("slurm_table_cleaned.parquet")
df

,id,start_date,end_date,node,nodetypes,numnodes,numcores,submit,state
0,1,2021-12-26 22:06:31,2021-12-31 22:06:50,r13n5,normal(1),1,16,1640538678,TIMEOUT
1,2,2021-12-26 22:06:43,2021-12-31 22:06:50,r14n27,normal(1),1,16,1640538678,TIMEOUT
2,3,2021-12-26 22:06:43,2021-12-31 22:06:50,r15n12,normal(1),1,16,1640538678,TIMEOUT
3,4,2021-12-26 22:06:43,2021-12-31 22:06:50,r10n14,normal(1),1,16,1640538678,TIMEOUT
4,5,2021-12-26 22:06:43,2021-12-31 22:06:50,r10n30,normal(1),1,16,1640538678,TIMEOUT
...,...,...,...,...,...,...,...,...,...
1596960,2323557,2022-11-01 12:58:19,2022-11-01 12:59:01,r14n20,normal(1),1,16,1667310861,COMPLETED
1596961,2323558,2022-11-01 12:58:19,2022-11-01 12:59:18,r14n21,normal(1),1,16,1667310866,COMPLETED
1596962,2323559,2022-11-01 12:55:57,2022-11-01 12:58:54,r28n1,gpu_titanrtx_shared(1),1,6,1667310957,CANCELLED
1596963,2323560,2022-11-01 12:56:17,2022-11-01 12:56:24,r13n10,shared(1),1,6,1667310972,FAILED
1596964,2323561,2022-11-01 12:56:45,2022-11-01 12:58:12,r28n1,gpu_titanrtx_shared(1),1,6,1667311005,FAILED

In [4]:
df = pd.read_csv("cloud_outages_dataset.csv")
df.columns

Index(['incident_id', 'cloud_provider', 'region', 'service', 'service_subtype',
       'start_time', 'end_time', 'duration_minutes', 'severity', 'status',
       'root_cause_category', 'root_cause_description',
       'number_of_customers_affected', 'estimated_revenue_loss_usd',
       'sla_violation', 'region_impact_score', 'service_impact_score',
       'ticket_count', 'ticket_response_time_minutes',
       'ticket_resolution_time_minutes', 'monitoring_alerts_triggered',
       'detection_method', 'mitigation_action', 'number_of_engineers_involved',
       'engineer_response_time_minutes', 'communication_channels_used',
       'public_status_page_updated', 'status_page_update_count',
       'user_feedback_score', 'post_mortem_completed', 'post_mortem_link',
       'is_recurrent_issue', 'previous_incident_id', 'external_factors',
       'scheduled_maintenance_conflict', 'patch_applied',
       'system_load_before_outage', 'system_load_after_outage',
       'backup_system_triggered', 'notes'],
      dtype='object')

In [5]:
df

,incident_id,cloud_provider,region,service,service_subtype,start_time,end_time,duration_minutes,severity,status,...,post_mortem_link,is_recurrent_issue,previous_incident_id,external_factors,scheduled_maintenance_conflict,patch_applied,system_load_before_outage,system_load_after_outage,backup_system_triggered,notes
0,aeb380d2-6559-4d99-abfb-17e1c45e831b,AWS,europe-west2,Storage,S3,2025-06-30 10:18:08.524480,2025-06-30 13:15:08.524480,177,Low,Monitoring,...,NaN,No,NaN,NaN,No,No,40,46,Yes,Simulated note
1,ddf7e3a0-f44d-4c94-ae32-189213321e2d,IBM,asia-southeast1,AI/ML,RDS,2025-06-28 10:18:08.524591,2025-06-28 20:52:08.524591,634,Low,Investigating,...,NaN,No,NaN,Weather,Yes,No,45,55,Yes,Simulated note
2,b17b9c80-94a0-4ca5-b52f-f1e7853b1240,AWS,europe-west2,Storage,S3,2025-06-01 10:18:08.524638,2025-06-01 14:36:08.524638,258,High,Resolved,...,NaN,No,NaN,DDoS,No,Yes,61,74,No,Simulated note
3,c856b404-e22e-4f84-8bed-9b1512adc9b5,AWS,asia-southeast1,Compute,Lambda,2025-11-30 10:18:08.524678,2025-11-30 19:21:08.524678,543,Medium,Resolved,...,NaN,Yes,NaN,Weather,No,Yes,48,97,Yes,Simulated note
4,42a85996-663a-4f92-94e1-0f205a06db01,IBM,asia-southeast1,AI/ML,Cloud Functions,2025-02-16 10:18:08.524719,2025-02-16 21:03:08.524719,645,Medium,Monitoring,...,NaN,No,NaN,DDoS,No,No,23,75,Yes,Simulated note
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2c5b0605-1c5f-4e71-8aff-7dab9221c9f1,AWS,us-west-2,Networking,RDS,2025-12-01 10:18:11.651560,2025-12-01 10:33:11.651560,15,Low,Monitoring,...,NaN,No,NaN,DDoS,No,No,12,94,No,Simulated note
49996,aab03d24-cf9e-40f7-bebf-69b3e3ab29fd,Azure,us-east-1,AI/ML,BigQuery,2025-12-27 10:18:11.651587,2025-12-27 12:02:11.651587,104,Critical,Investigating,...,NaN,No,NaN,Weather,Yes,Yes,12,45,No,Simulated note
49997,740000a8-c9c5-4a1f-b455-948cc64da7de,AWS,europe-west2,Compute,BigQuery,2025-10-16 10:18:11.651615,2025-10-16 20:08:11.651615,590,Medium,Investigating,...,NaN,No,NaN,Vendor,No,Yes,23,62,Yes,Simulated note
49998,8c9bfbd1-9adb-45b6-add4-e7af08af4b22,Azure,us-west-2,Networking,S3,2025-04-05 10:18:11.651645,2025-04-05 15:48:11.651645,330,High,Investigating,...,NaN,Yes,NaN,NaN,Yes,Yes,67,77,No,Simulated note
49999,b94c1c5b-4b40-4d53-8c64-29f2cb38461e,IBM,us-west-2,AI/ML,BigQuery,2025-08-29 10:18:11.651680,2025-08-29 21:45:11.651680,687,High,Investigating,...,NaN,Yes,NaN,DDoS,No,No,87,16,No,Simulated note

In [8]:
df = pd.read_csv("realAWSCloudwatch/ec2_cpu_utilization_24ae8d.csv")
df

                timestamp  value
0     2014-02-14 14:30:00  0.132
1     2014-02-14 14:35:00  0.134
2     2014-02-14 14:40:00  0.134
3     2014-02-14 14:45:00  0.134
4     2014-02-14 14:50:00  0.134
...                   ...    ...
4027  2014-02-28 14:05:00  0.132
4028  2014-02-28 14:10:00  0.134
4029  2014-02-28 14:15:00  0.134
4030  2014-02-28 14:20:00  0.134
4031  2014-02-28 14:25:00  0.134

[4032 rows x 2 columns]

In [9]:
df = pd.read_csv("realAWSCloudwatch/grok_asg_anomaly.csv")
df

                timestamp    value
0     2014-01-16 00:00:00  33.5573
1     2014-01-16 00:05:00  33.4460
2     2014-01-16 00:10:00  33.4447
3     2014-01-16 00:15:00  33.3333
4     2014-01-16 00:20:00  33.4447
...                   ...      ...
4616  2014-02-01 00:40:00   0.3380
4617  2014-02-01 00:45:00   0.0000
4618  2014-02-01 00:50:00   0.0000
4619  2014-02-01 00:55:00   0.0000
4620  2014-02-01 01:00:00   0.3340

[4621 rows x 2 columns]

In [11]:
import json

with open("data/combined_windows.json") as f:
    combined_windows = json.load(f)

combined_windows

{'artificialNoAnomaly/art_daily_no_noise.csv': [],
 'artificialNoAnomaly/art_daily_perfect_square_wave.csv': [],
 'artificialNoAnomaly/art_daily_small_noise.csv': [],
 'artificialNoAnomaly/art_flatline.csv': [],
 'artificialNoAnomaly/art_noisy.csv': [],
 'artificialWithAnomaly/art_daily_flatmiddle.csv': [['2014-04-10 07:15:00.000000',
   '2014-04-11 16:45:00.000000']],
 'artificialWithAnomaly/art_daily_jumpsdown.csv': [['2014-04-10 16:15:00.000000',
   '2014-04-12 01:45:00.000000']],
 'artificialWithAnomaly/art_daily_jumpsup.csv': [['2014-04-10 16:15:00.000000',
   '2014-04-12 01:45:00.000000']],
 'artificialWithAnomaly/art_daily_nojump.csv': [['2014-04-10 16:15:00.000000',
   '2014-04-12 01:45:00.000000']],
 'artificialWithAnomaly/art_increase_spike_density.csv': [['2014-04-07 06:25:00.000000',
   '2014-04-08 15:55:00.000000']],
 'artificialWithAnomaly/art_load_balancer_spikes.csv': [['2014-04-10 11:50:00.000000',
   '2014-04-11 21:20:00.000000']],
 'realAWSCloudwatch/ec2_cpu_utilization_24ae8d.csv': [['2014-02-26 13:45:00.000000',
   '2014-02-27 06:25:00.000000'],
  ['2014-02-27 08:55:00.000000', '2014-02-28 01:35:00.000000']],
 'realAWSCloudwatch/ec2_cpu_utilization_53ea38.csv': [['2014-02-19 10:50:00.000000',
   '2014-02-20 03:30:00.000000'],
  ['2014-02-23 11:45:00.000000', '2014-02-24 04:25:00.000000']],
 'realAWSCloudwatch/ec2_cpu_utilization_5f5533.csv': [['2014-02-18 16:02:00.000000',
   '2014-02-19 08:42:00.000000'],
  ['2014-02-24 10:17:00.000000', '2014-02-25 02:57:00.000000']],
 'realAWSCloudwatch/ec2_cpu_utilization_77c1ca.csv': [['2014-04-08 17:30:00.000000',
   '2014-04-10 03:00:00.000000']],
 'realAWSCloudwatch/ec2_cpu_utilization_825cc2.csv': [['2014-04-15 07:24:00.000000',
   '2014-04-16 11:54:00.000000']],
 'realAWSCloudwatch/ec2_cpu_utilization_ac20cd.csv': [['2014-04-14 07:49:00.000000',
   '2014-04-15 17:34:00.000000']],
 'realAWSCloudwatch/ec2_cpu_utilization_c6585a.csv': [],
 'realAWSCloudwatch/ec2_cpu_utilization_fe7f93.csv': [['2014-02-17 00:37:00.000000',
   '2014-02-17 11:47:00.000000'],
  ['2014-02-21 18:27:00.000000', '2014-02-22 05:37:00.000000'],
  ['2014-02-23 09:42:00.000000', '2014-02-23 20:52:00.000000']],
 'realAWSCloudwatch/ec2_disk_write_bytes_1ef3de.csv': [['2014-03-10 01:29:00.000000',
   '2014-03-11 16:49:00.000000']],
 'realAWSCloudwatch/ec2_disk_write_bytes_c0d644.csv': [['2014-04-08 19:55:00.000000',
   '2014-04-09 07:05:00.000000'],
  ['2014-04-10 09:00:00.000000', '2014-04-10 20:10:00.000000'],
  ['2014-04-12 21:25:00.000000', '2014-04-13 08:35:00.000000']],
 'realAWSCloudwatch/ec2_network_in_257a54.csv': [['2014-04-14 23:59:00.000000',
   '2014-04-16 09:29:00.000000']],
 'realAWSCloudwatch/ec2_network_in_5abac7.csv': [['2014-03-10 09:06:00.000000',
   '2014-03-11 04:46:00.000000'],
  ['2014-03-12 11:11:00.000000', '2014-03-13 06:51:00.000000']],
 'realAWSCloudwatch/elb_request_count_8c0756.csv': [['2014-04-12 09:04:00.000000',
   '2014-04-13 01:44:00.000000'],
  ['2014-04-22 11:14:00.000000', '2014-04-23 03:54:00.000000']],
 'realAWSCloudwatch/grok_asg_anomaly.csv': [['2014-01-20 02:05:00.000000',
   '2014-01-20 14:55:00.000000'],
  ['2014-01-21 04:20:00.000000', '2014-01-21 17:10:00.000000'],
  ['2014-01-28 18:20:00.000000', '2014-01-29 07:10:00.000000']],
 'realAWSCloudwatch/iio_us-east-1_i-a2eb1cd9_NetworkIn.csv': [['2013-10-10 10:35:00.000000',
   '2013-10-10 15:45:00.000000'],
  ['2013-10-10 18:05:00.000000', '2013-10-10 23:15:00.000000']],
 'realAWSCloudwatch/rds_cpu_utilization_cc0c53.csv': [['2014-02-24 22:50:00.000000',
   '2014-02-25 15:35:00.000000'],
  ['2014-02-26 16:30:00.000000', '2014-02-27 09:10:00.000000']],
 'realAWSCloudwatch/rds_cpu_utilization_e47b3b.csv': [['2014-04-12 22:32:00.000000',
   '2014-04-13 15:12:00.000000'],
  ['2014-04-18 15:07:00.000000', '2014-04-19 07:47:00.000000']],
 'realAdExchange/exchange-2_cpc_results.csv': [['2011-07-11 04:00:01.000000',
   '2011-07-17 22:00:01.000000']],
 'realAdExchange/exchange-2_cpm_results.csv': [['2011-07-24 14:00:01.000000',
   '2011-07-27 22:00:01.000000'],
  ['2011-08-09 00:00:01.000000', '2011-08-12 09:00:01.000000']],
 'realAdExchange/exchange-3_cpc_results.csv': [['2011-07-13 09:15:01.000000',
   '2011-07-15 11:15:01.000000'],
  ['2011-07-19 09:15:01.000000', '2011-07-21 11:15:01.000000'],
  ['2011-08-12 07:15:01.000000', '2011-08-14 13:15:01.000000']],
 'realAdExchange/exchange-3_cpm_results.csv': [['2011-08-16 10:15:01.000000',
   '2011-08-23 00:15:01.000000']],
 'realAdExchange/exchange-4_cpc_results.csv': [['2011-07-15 06:15:01.000000',
   '2011-07-17 12:15:01.000000'],
  ['2011-08-01 07:15:01.000000', '2011-08-03 15:15:01.000000'],
  ['2011-08-22 05:15:01.000000', '2011-08-24 11:15:01.000000']],
 'realAdExchange/exchange-4_cpm_results.csv': [['2011-07-15 13:15:01.000000',
   '2011-07-17 05:15:01.000000'],
  ['2011-07-31 11:15:01.000000', '2011-08-02 05:15:01.000000'],
  ['2011-08-22 12:15:01.000000', '2011-08-24 04:15:01.000000'],
  ['2011-08-27 17:15:01.000000', '2011-08-29 09:15:01.000000']],
 'realKnownCause/ambient_temperature_system_failure.csv': [['2013-12-15 07:00:00.000000',
   '2013-12-30 09:00:00.000000'],
  ['2014-03-29 15:00:00.000000', '2014-04-20 22:00:00.000000']],
 'realKnownCause/cpu_utilization_asg_misconfiguration.csv': [['2014-07-10 12:29:00.000000',
   '2014-07-15 17:19:00.000000']],
 'realKnownCause/ec2_request_latency_system_failure.csv': [['2014-03-14 03:31:00.000000',
   '2014-03-14 14:41:00.000000'],
  ['2014-03-18 17:06:00.000000', '2014-03-19 04:16:00.000000'],
  ['2014-03-20 21:26:00.000000', '2014-03-21 03:41:00.000000']],
 'realKnownCause/machine_temperature_system_failure.csv': [['2013-12-10 06:25:00.000000',
   '2013-12-12 05:35:00.000000'],
  ['2013-12-15 17:50:00.000000', '2013-12-17 17:00:00.000000'],
  ['2014-01-27 14:20:00.000000', '2014-01-29 13:30:00.000000'],
  ['2014-02-07 14:55:00.000000', '2014-02-09 14:05:00.000000']],
 'realKnownCause/nyc_taxi.csv': [['2014-10-30 15:30:00.000000',
   '2014-11-03 22:30:00.000000'],
  ['2014-11-25 12:00:00.000000', '2014-11-29 19:00:00.000000'],
  ['2014-12-23 11:30:00.000000', '2014-12-27 18:30:00.000000'],
  ['2014-12-29 21:30:00.000000', '2015-01-03 04:30:00.000000'],
  ['2015-01-24 20:30:00.000000', '2015-01-29 03:30:00.000000']],
 'realKnownCause/rogue_agent_key_hold.csv': [['2014-07-15 04:35:00.000000',
   '2014-07-15 13:25:00.000000'],
  ['2014-07-17 05:50:00.000000', '2014-07-18 06:45:00.000000']],
 'realKnownCause/rogue_agent_key_updown.csv': [['2014-07-14 17:00:00.000000',
   '2014-07-15 15:00:00.000000'],
  ['2014-07-16 21:50:00.000000', '2014-07-17 19:50:00.000000']],
 'realTraffic/TravelTime_387.csv': [['2015-07-27 10:56:00.000000',
   '2015-07-31 18:01:00.000000'],
  ['2015-08-17 11:51:00.000000', '2015-08-20 01:54:00.000000'],
  ['2015-08-31 15:44:00.000000', '2015-09-01 13:06:00.000000']],
 'realTraffic/TravelTime_451.csv': [['2015-08-09 17:57:00.000000',
   '2015-08-12 20:01:00.000000']],
 'realTraffic/occupancy_6005.csv': [['2015-09-14 17:45:00.000000',
   '2015-09-15 17:24:00.000000']],
 'realTraffic/occupancy_t4013.csv': [['2015-09-16 00:59:00.000000',
   '2015-09-16 13:19:00.000000'],
  ['2015-09-17 00:20:00.000000', '2015-09-17 13:10:00.000000']],
 'realTraffic/speed_6005.csv': [['2015-09-16 18:40:00.000000',
   '2015-09-17 16:24:00.000000']],
 'realTraffic/speed_7578.csv': [['2015-09-11 15:34:00.000000',
   '2015-09-11 17:54:00.000000'],
  ['2015-09-15 13:26:00.000000', '2015-09-15 15:54:00.000000'],
  ['2015-09-16 13:04:00.000000', '2015-09-16 15:20:00.000000'],
  ['2015-09-16 16:00:00.000000', '2015-09-16 18:20:00.000000']],
 'realTraffic/speed_t4013.csv': [['2015-09-16 00:44:00.000000',
   '2015-09-16 13:14:00.000000'],
  ['2015-09-17 00:30:00.000000', '2015-09-17 13:30:00.000000']],
 'realTweets/Twitter_volume_AAPL.csv': [['2015-03-03 04:37:53.000000',
   '2015-03-04 13:37:53.000000'],
  ['2015-03-09 01:02:53.000000', '2015-03-10 10:02:53.000000'],
  ['2015-03-15 10:27:53.000000', '2015-03-16 19:27:53.000000'],
  ['2015-03-30 10:57:53.000000', '2015-03-31 19:57:53.000000']],
 'realTweets/Twitter_volume_AMZN.csv': [['2015-03-05 03:22:53.000000',
   '2015-03-06 12:12:53.000000'],
  ['2015-03-11 04:32:53.000000', '2015-03-12 13:22:53.000000'],
  ['2015-04-01 05:32:53.000000', '2015-04-02 14:22:53.000000'],
  ['2015-04-07 12:27:53.000000', '2015-04-08 21:17:53.000000']],
 'realTweets/Twitter_volume_CRM.csv': [['2015-03-08 21:02:53.000000',
   '2015-03-10 17:12:53.000000'],
  ['2015-03-19 01:02:53.000000', '2015-03-20 21:12:53.000000'],
  ['2015-03-25 21:02:53.000000', '2015-03-27 17:12:53.000000']],
 'realTweets/Twitter_volume_CVS.csv': [['2015-03-03 23:32:53.000000',
   '2015-03-06 12:27:53.000000'],
  ['2015-03-25 21:37:53.000000', '2015-03-27 06:37:53.000000'],
  ['2015-04-14 06:07:53.000000', '2015-04-15 15:07:53.000000']],
 'realTweets/Twitter_volume_FB.csv': [['2015-03-14 22:12:53.000000',
   '2015-03-17 16:02:53.000000'],
  ['2015-04-02 08:52:53.000000', '2015-04-05 02:42:53.000000']],
 'realTweets/Twitter_volume_GOOG.csv': [['2015-03-13 03:52:53.000000',
   '2015-03-15 08:57:53.000000'],
  ['2015-03-22 06:22:53.000000', '2015-03-23 15:22:53.000000'],
  ['2015-03-31 12:57:53.000000', '2015-04-01 21:57:53.000000']],
 'realTweets/Twitter_volume_IBM.csv': [['2015-03-22 13:22:53.000000',
   '2015-03-25 07:32:53.000000'],
  ['2015-04-19 11:02:53.000000', '2015-04-22 05:12:53.000000']],
 'realTweets/Twitter_volume_KO.csv': [['2015-03-19 15:12:53.000000',
   '2015-03-21 11:12:53.000000'],
  ['2015-04-08 01:42:53.000000', '2015-04-09 21:42:53.000000'],
  ['2015-04-13 16:52:53.000000', '2015-04-15 12:52:53.000000']],
 'realTweets/Twitter_volume_PFE.csv': [['2015-03-02 04:52:53.000000',
   '2015-03-03 13:52:53.000000'],
  ['2015-03-03 18:02:53.000000', '2015-03-05 03:02:53.000000'],
  ['2015-03-13 03:27:53.000000', '2015-03-14 12:27:53.000000'],
  ['2015-04-07 07:12:53.000000', '2015-04-08 16:12:53.000000']],
 'realTweets/Twitter_volume_UPS.csv': [['2015-03-02 11:17:53.000000',
   '2015-03-03 13:37:53.000000'],
  ['2015-03-03 21:57:53.000000', '2015-03-05 00:17:53.000000'],
  ['2015-03-05 02:12:53.000000', '2015-03-06 04:32:53.000000'],
  ['2015-03-24 05:07:53.000000', '2015-03-25 07:27:53.000000'],
  ['2015-03-29 03:17:53.000000', '2015-03-30 05:37:53.000000']]}